version: '3.3'
services:
   picframe:
     image: P8ntBal1551/pictureframe:latest
     ports:
      - "5000:5000"
     volumes:
       - *Your image directory*:/app/config/images
       - /docker/pictureframe:/app/config
     restart: always
     environment:
       - REFRESH_INTERVAL=30